### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by sd2k** [sd2k/newrelic#7]
I'm no longer at a job where we use New Relic, but I've signed up for a free New Relic account which lets me run tests again, at least.

We should add CI using a new NR account specific for this crate. It'll need the New Relic C SDK (should we add that as a submodule to this repository?) so we can build and run the daemon first. Ideally we'd have some way of outputting the daemon logs if anything goes wrong, too.

We should run `cargo clippy`, `cargo fmt` and `cargo test`.

**Comment by bobbyrward** [comment]
If you run into any issues with this, I have an unfortunate amount of experience with github actions.
